_default: target_lib host_lib

include ../../settings.mak

LIB_NAME=core_unix
BUILD_SUBDIR_NAME=libcore

include $(LIB_FRONT_MAK)

C_SOURCES += port_debug_io.c
C_SOURCES += port_timer.c

include $(LIB_BACK_MAK)


