
HOST_ADDR2LINE	:=$(HOST_PREFIX)addr2line
HOST_AR		:=$(HOST_PREFIX)ar
HOST_AS		:=$(HOST_PREFIX)as
HOST_CXX	:=$(HOST_PREFIX)c++
HOST_CXXFILT	:=$(HOST_PREFIX)c++filt
HOST_CPP	:=$(HOST_PREFIX)cpp
HOST_ELFEDIT	:=$(HOST_PREFIX)-elfedit
HOST_GXX	:=$(HOST_PREFIX)g++
HOST_GCC	:=$(HOST_PREFIX)gcc
HOST_RANLIB	:=$(HOST_PREFIX)ranlib
HOST_LD		:=$(HOST_PREFIX)ld
HOST_NM		:=$(HOST_PREFIX)nm
HOST_OBJDUMP	:=$(HOST_PREFIX)objdump
HOST_OBJCOPY	:=$(HOST_PREFIX)objcopy
HOST_SIZE	:=$(HOST_PREFIX)size
HOST_STRIP	:=$(HOST_PREFIX)strip








