
TARGET_ADDR2LINE	:=$(CROSS_COMPILE)-addr2line
TARGET_AR		:=$(CROSS_COMPILE)-ar
TARGET_AS		:=$(CROSS_COMPILE)-as
TARGET_CXX		:=$(CROSS_COMPILE)-c++
TARGET_CXXFILT		:=$(CROSS_COMPILE)-c++filt
TARGET_CPP		:=$(CROSS_COMPILE)-cpp
TARGET_ELFEDIT		:=$(CROSS_COMPILE)-elfedit
TARGET_GXX		:=$(CROSS_COMPILE)-g++
TARGET_GCC		:=$(CROSS_COMPILE)-gcc
TARGET_RANLIB		:=$(CROSS_COMPILE)-ranlib
TARGET_LD		:=$(CROSS_COMPILE)-ld
TARGET_NM		:=$(CROSS_COMPILE)-nm
TARGET_OBJDUMP		:=$(CROSS_COMPILE)-objdump
TARGET_OBJCOPY		:=$(CROSS_COMPILE)-objcopy
TARGET_SIZE		:=$(CROSS_COMPILE)-size
TARGET_STRIP		:=$(CROSS_COMPILE)-strip








