name: Linux Build

jobs:
	smoke_test:
		runs-on: ubuntu-slim
		steps:
			- name: Checkout
		  	  uses: actions/checkout@v4

			- name: GenerateMakefile
			- run: [
			       source ./project_settings.sh
			       bash ./create_venv.sh
			       source .venv/bin/activate
			       bash ./gen_makefile.sh ./build.d
			  ]

			- name: RunMake
			- run: [
			       cd ./build.d/linux
			       make all
			  ]
			  
			       
			       
		